import os
import time
import base64
import requests
from openai import OpenAI
from dotenv import load_dotenv

# ==========================================
# 1. SETUP CONFIGURATION & ENVS
# ==========================================
load_dotenv()
OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")

if not OPENROUTER_API_KEY:
    raise ValueError("API Key missing! Make sure OPENROUTER_API_KEY is configured inside your .env file.")

# Define local paths
SAMPLE_IMAGE_PATH = "my_style.jpg"  # Your reference local picture
PROMPTS_FILE = "prompts.txt"        # Your custom subjects file
OUTPUT_DIR = "automated_outputs"    # Where images will land
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Recommended Premium Models
VISION_MODEL = "google/gemini-2.5-flash"
IMAGE_MODEL = "black-forest-labs/flux.2-pro"

# Helper to change image into Base64 format for OpenRouter
def encode_image(image_path):
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Missing local style image at: {image_path}")
    with open(image_path, "rb") as image_file:
        return base64.b64encode(image_file.read()).decode('utf-8')

# Initialize OpenAI client pointed to OpenRouter
client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=OPENROUTER_API_KEY
)

# ==========================================
# 2. VISION STEP: CAPTURE THE BASELINE STYLE
# ==========================================
print(f"✨ Step 1: Analyzing aesthetic style using {VISION_MODEL}...")
base64_image = encode_image(SAMPLE_IMAGE_PATH)

try:
    vision_response = client.chat.completions.create(
        model=VISION_MODEL,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": "Analyze the artistic style, color palette, lighting, and texture of this image. Provide a precise, 2-sentence description focusing strictly on the visual aesthetic so it can act as a style prompt modifier."
                    },
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}
                    }
                ]
            }
        ]
    )
    extracted_style = vision_response.choices[0].message.content
    print(f"\n🎨 Extracted Style Anchor:\n> {extracted_style}\n")
except Exception as e:
    print(f"❌ Failed to parse style image: {e}")
    exit()

# ==========================================
# 3. FILE PARSING: LOAD YOUR LOOP PROMPTS
# ==========================================
if not os.path.exists(PROMPTS_FILE):
    with open(PROMPTS_FILE, "w", encoding="utf-8") as f:
        f.write("A stunning landscape painting\nA high-tech cybernetic robot\n")
    print(f"ℹ️ Created a blank layout file: '{PROMPTS_FILE}'. Populate it and rerun.")
    exit()

with open(PROMPTS_FILE, "r", encoding="utf-8") as f:
    subjects = [line.strip() for line in f if line.strip() and not line.startswith("#")]

print(f"📦 Successfully loaded {len(subjects)} items from your queue.\n")

# ==========================================
# 4. LOOP GENERATION PIPELINE
# ==========================================
print(f"🚀 Initializing generation queue on model: {IMAGE_MODEL}...")

for index, subject in enumerate(subjects):
    # We combine your custom text line with the style generated by the Vision step
    final_prompt = f"{subject}, {extracted_style}"
    print(f"[{index + 1}/{len(subjects)}] Generating target: '{subject[:40]}...'")

    response_data = None  # Instantiated safely to avoid runtime unbound exceptions

    try:
        headers = {
            "Authorization": f"Bearer {OPENROUTER_API_KEY}",
            "Content-Type": "application/json"
        }

        payload = {
            "model": IMAGE_MODEL,
            "prompt": final_prompt,
            "output_format": "png"
        }

        # Call the unified OpenRouter Image API directly
        response = requests.post(
            "https://openrouter.ai/api/v1/images",
            headers=headers,
            json=payload
        )

        response_data = response.json()

        if "data" in response_data and len(response_data["data"]) > 0:
            img_item = response_data["data"][0]
            file_path = os.path.join(OUTPUT_DIR, f"generation_{index + 1}.png")

            # OpenRouter standard returns either direct URLs or native Base64 payloads
            if "b64_json" in img_item:
                image_bytes = base64.b64decode(img_item["b64_json"])
                with open(file_path, "wb") as f:
                    f.write(image_bytes)
            else:
                image_url = img_item["url"]
                image_bytes = requests.get(image_url).content
                with open(file_path, "wb") as f:
                    f.write(image_bytes)

            print(f"💾 File Saved -> {file_path}")
        else:
            print(f"⚠️ Warning: Could not find valid output data block on index {index + 1}.")
            print(f"Response Details: {response_data}")

    except Exception as e:
        print(f"❌ Error occurred generating index {index + 1}: {e}")
        if response_data is not None:
            print(f"🔧 Debug response info: {response_data}")
        continue

    # 4-second safety cooldown to seamlessly handle RPM limits
    time.sleep(4)

print("\n🎉 Process completed! Your custom styled library is ready inside 'automated_outputs'.")
